### ISSUE TITLE
Suggestion: Go back to White theme, or provide option

### ISSUE THREAD

**Issue by sharkcrayon** [8base/old-documentation#23]
I find your new dark theme for your documentation _a lot_ less readable, and a lot less approachable, to the point where I'm editing the CSS so I can read it again with a white background. It might be worth asking the 8base community if the dark theme is actually an improvement for them. I personally would very much appreciate a light vs dark theme option, so I could continue happily reading the docs with a light - and legible - theme.

**Comment by sebscholl** [comment]
Hi @sharkcrayon - sorry that you feel this way. When we next revisit the design of our documentation site, we'll consider this.

Thanks
