### ISSUE TITLE
404's on "Useful Guides" links when following through the "Overview" section of left sidebar

### ISSUE THREAD

**Issue by Fomich3000** [8base/old-documentation#34]
1. Go to https://docs.8base.com/docs/
2. Follow the "Overview" section through left sidebar (without refreshing page).
3. Try to follow any link under the "Useful Guides" section (e.g. "Quick Start")

![image](https://user-images.githubusercontent.com/38749960/91231405-d91c1280-e735-11ea-822f-5e0e74e1cf00.png)

Expected: opening of requested page.; 
Actual: blank page with 404 in console.

![image](https://user-images.githubusercontent.com/38749960/91231805-8f7ff780-e736-11ea-91e7-0d9ee5ff0dad.png)

Additional info: it's works OK after refreshing page on "Overview" section or get back after 404 and opening link again.

**Comment by Selnapenek** [comment]
resolved
