### ISSUE TITLE
Broken "Quickstart guide", "Auth0" links in SDK section

### ISSUE THREAD

**Issue by markforestson** [8base/old-documentation#4]
Non-working links in [SDK](https://docs.8base.com/development-tools/sdk)
- https://docs.8base.com/v1.0/docs/quickstart
![image](https://user-images.githubusercontent.com/48910827/64332693-a8e7db00-cfdd-11e9-9e68-e76547bbccd2.png)

- https://auth0.com/Auth0
![image](https://user-images.githubusercontent.com/48910827/64332553-72aa5b80-cfdd-11e9-80c9-ec8fc47829b1.png)

**Comment by sebscholl** [comment]
thanks @markforestson ! Updating these now.
